import json
import os
from typing import Dict, Any

class SkillTree:
    """
    Manages the agent's dynamically generated tools (skills).
    The more you use Nexus, the more tools it generates for itself.
    """
    def __init__(self, skill_dir: str = ".nexus/skills"):
        self.skill_dir = skill_dir
        self.skills: Dict[str, Any] = {}
        self._load()

    def _load(self):
        """Loads available skills from the local .nexus directory."""
        if not os.path.exists(self.skill_dir):
            os.makedirs(self.skill_dir, exist_ok=True)
            return

        for filename in os.listdir(self.skill_dir):
            if filename.endswith(".json"):
                try:
                    with open(os.path.join(self.skill_dir, filename), "r") as f:
                        skill = json.load(f)
                        self.skills[skill.get("name", filename)] = skill
                except Exception:
                    continue

    def add_skill(self, name: str, description: str, code_snippet: str):
        """
        Dynamically saves a new skill generated by the LLM.
        """
        skill_data = {
            "name": name,
            "description": description,
            "code": code_snippet,
            "version": "1.0"
        }
        filepath = os.path.join(self.skill_dir, f"{name}.json")
        with open(filepath, "w") as f:
            json.dump(skill_data, f, indent=4)
        
        self.skills[name] = skill_data

    def list_skills(self) -> str:
        """Returns a string list of all currently loaded skills."""
        if not self.skills:
            return "No custom skills acquired yet."
        
        return "\n".join(f"- **{s}**: {data.get('description', '')}" for s, data in self.skills.items())

    def get_stats(self) -> Dict[str, int]:
        return {
            "total_skills": len(self.skills)
        }
